input {
  tcp {
    port => 5000
    type => syslog
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOST:http://localhost}:${ELASTICSEARCH_PORT:9200}"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}
